version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Mimosito04
      MYSQL_DATABASE: libros_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Mimosito04
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "5506:3306"
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Exponés el puerto 80 localmente
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - frontend
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Mimosito04

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: mysql+pymysql://root:Mimosito04@db:3306/libros_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mysql_data: