version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: libros_db
      MYSQL_ROOT_PASSWORD: valentin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3333:3000"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
