# Generated by Django 5.2 on 2025-07-23 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="libro",
            name="genero",
        ),
        migrations.AlterField(
            model_name="libro",
            name="autor",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="libro",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="LibroGenero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.genero"
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.libro"
                    ),
                ),
            ],
            options={
                "unique_together": {("libro", "genero")},
            },
        ),
        migrations.AddField(
            model_name="libro",
            name="generos",
            field=models.ManyToManyField(
                related_name="libros", through="app.LibroGenero", to="app.genero"
            ),
        ),
    ]
